### ISSUE TITLE
Backgroung

### ISSUE THREAD

**Issue by renatords** [juancruzmdq/LocationRequestManager#1]
Hi,

This control works when app is in background? Thanks

**Comment by juancruzmdq** [comment]
Hi,
yes, you have to set kCLAuthorizationStatusAuthorizedAlways in your plist

https://github.com/juancruzmdq/LocationRequestManager#request-location-authorization

**Comment by renatords** [comment]
Thank you very much. I will test it must apply even if not actively send the location to a server.

**Comment by juancruzmdq** [comment]
Hi, did you have the opportunity to test it?
